### ISSUE TITLE
Bengali Translation

### ISSUE THREAD

**Issue by wvsr** [semver/semver.org#428] opened 2023-08-30 12:41 UTC
Being Bengali is one of the most speaking languages (ranked 6th). It is quite disheartening for me that there is no support/translation for Bengali. I am working on the Bengali translation.

**Comment by JohnTitor** [comment] 2023-11-23 04:50
Duplicate of https://github.com/semver/semver.org/issues/417, feel free to continue the discussion there!

**Closed as not planned by JohnTitor** 2023-11-23 04:50 UTC
