### ISSUE TITLE
consider allowing the '.' character as first character of the special version number

### ISSUE THREAD

**Issue by stoicflame** [semver/semver.org#32] opened 2011-05-04 17:03 UTC
It would be really nice to allow the '.' character as part of the "special version number" so that it could be compatible with with the OSGi semantic versioning definition at http://www.osgi.org/wiki/uploads/Links/SemanticVersioning.pdf. 

There are a lot of open-source Java projects that are versioned according to the OSGi semantic versioning definition, e.g.

1.0.0.BUILD

and

1.0.0.RELEASE

**Comment by mojombo** [comment] 2011-09-07 07:14
Dupe of #33 where more discussion has happened.

**Closed as completed by mojombo** 2011-09-07 07:14 UTC
